//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public class a
    {

    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string BirthPlace { get; set; }
    }
        public void AddData(string FirstName, string LastName, string Address, string BirthPlace)
        {
            EmployeeManagementEntities3 db = new EmployeeManagementEntities3();
            string sql = "INSERT INTO Account(FirstName,LastName,Address,BirthPlace) VALUES(N'" + FirstName +
                "','" + LastName + "',N'" + Address + "',N'" + BirthPlace + "')";
            SqlConnection con = db.GetConnection();
            SqlCommand cmd = new SqlCommand(sql, con);
            con.Open();
            cmd.ExecuteNonQuery();
            cmd.Dispose();
            con.Close();

        }
    }
}
