//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class EmployeeManagementEntities3 : DbContext
    {
        public EmployeeManagementEntities3()
            : base("name=EmployeeManagementEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a.Employee> Employees { get; set; }
        public virtual DbSet<User> Users { get; set; }

        internal SqlConnection GetConnection()
        {
            throw new NotImplementedException();
        }
    }
}
